apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task3-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      env: production 